<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/01/21 16:17:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=hrm',
  'username' => 'root',
  'password' => 'prasad',
  'port' => 3306,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
