<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNotice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_notice');
        $this->hasColumn('notice_code', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('notice_name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('notice_name_si', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('notice_name_ta', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('notice_desc', 'string', 250, array(
             'type' => 'string',
             'length' => '250',
             ));
        $this->hasColumn('notice_desc_si', 'string', 250, array(
             'type' => 'string',
             'length' => '250',
             ));
        $this->hasColumn('notice_desc_ta', 'string', 250, array(
             'type' => 'string',
             'length' => '250',
             ));
        $this->hasColumn('from_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('to_date', 'date', null, array(
             'type' => 'date',
             ));
    }

}